package com.irs.pojo;

public class News {
	
	/**
	 * 类别名
	 */
	private String typeName;
	
    public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.userid
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.pubtime
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    private String pubtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.typeid
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.imgurl
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.verify
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    private Integer verify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.fileid
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    private Integer fileid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.filename
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.fileurl
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    private String fileurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.username
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.userfullname
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    private String userfullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
	private String content;

    @Override
	public String toString() {
		return "News [id=" + id + ", title=" + title + ", userid=" + userid + ", pubtime=" + pubtime + ", typeid="
				+ typeid + ", imgurl=" + imgurl + ", verify=" + verify + ", fileid=" + fileid + ", filename=" + filename
				+ ", fileurl=" + fileurl + ", username=" + username + ", userfullname=" + userfullname + ", content="
				+ content + "]";
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.userid
     *
     * @return the value of news.userid
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.userid
     *
     * @param userid the value for news.userid
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.pubtime
     *
     * @return the value of news.pubtime
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public String getPubtime() {
        return pubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.pubtime
     *
     * @param pubtime the value for news.pubtime
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public void setPubtime(String pubtime) {
        this.pubtime = pubtime == null ? null : pubtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.typeid
     *
     * @return the value of news.typeid
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.typeid
     *
     * @param typeid the value for news.typeid
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.imgurl
     *
     * @return the value of news.imgurl
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.imgurl
     *
     * @param imgurl the value for news.imgurl
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.verify
     *
     * @return the value of news.verify
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public Integer getVerify() {
        return verify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.verify
     *
     * @param verify the value for news.verify
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public void setVerify(Integer verify) {
        this.verify = verify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.fileid
     *
     * @return the value of news.fileid
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.fileid
     *
     * @param fileid the value for news.fileid
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.filename
     *
     * @return the value of news.filename
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.filename
     *
     * @param filename the value for news.filename
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.fileurl
     *
     * @return the value of news.fileurl
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public String getFileurl() {
        return fileurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.fileurl
     *
     * @param fileurl the value for news.fileurl
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public void setFileurl(String fileurl) {
        this.fileurl = fileurl == null ? null : fileurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.username
     *
     * @return the value of news.username
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.username
     *
     * @param username the value for news.username
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.userfullname
     *
     * @return the value of news.userfullname
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public String getUserfullname() {
        return userfullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.userfullname
     *
     * @param userfullname the value for news.userfullname
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public void setUserfullname(String userfullname) {
        this.userfullname = userfullname == null ? null : userfullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param content the value for news.content
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}