package com.irs.mapper;

import com.irs.pojo.NewsType;
import com.irs.pojo.NewsTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    int countByExample(NewsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    int deleteByExample(NewsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    int insert(NewsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    int insertSelective(NewsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    List<NewsType> selectByExample(NewsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    NewsType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") NewsType record, @Param("example") NewsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    int updateByExample(@Param("record") NewsType record, @Param("example") NewsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    int updateByPrimaryKeySelective(NewsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_type
     *
     * @mbggenerated Tue Nov 27 14:35:59 CST 2018
     */
    int updateByPrimaryKey(NewsType record);
}