package com.irs.mapper;

import com.irs.pojo.TbVisit;
import com.irs.pojo.TbVisitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbVisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_visit
     *
     * @mbggenerated Thu Sep 20 15:21:34 CST 2018
     */
    int countByExample(TbVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_visit
     *
     * @mbggenerated Thu Sep 20 15:21:34 CST 2018
     */
    int deleteByExample(TbVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_visit
     *
     * @mbggenerated Thu Sep 20 15:21:34 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_visit
     *
     * @mbggenerated Thu Sep 20 15:21:34 CST 2018
     */
    int insert(TbVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_visit
     *
     * @mbggenerated Thu Sep 20 15:21:34 CST 2018
     */
    int insertSelective(TbVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_visit
     *
     * @mbggenerated Thu Sep 20 15:21:34 CST 2018
     */
    List<TbVisit> selectByExample(TbVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_visit
     *
     * @mbggenerated Thu Sep 20 15:21:34 CST 2018
     */
    TbVisit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_visit
     *
     * @mbggenerated Thu Sep 20 15:21:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbVisit record, @Param("example") TbVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_visit
     *
     * @mbggenerated Thu Sep 20 15:21:34 CST 2018
     */
    int updateByExample(@Param("record") TbVisit record, @Param("example") TbVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_visit
     *
     * @mbggenerated Thu Sep 20 15:21:34 CST 2018
     */
    int updateByPrimaryKeySelective(TbVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_visit
     *
     * @mbggenerated Thu Sep 20 15:21:34 CST 2018
     */
    int updateByPrimaryKey(TbVisit record);
}